import { Activity, HeartPulse, ShieldAlert, Wifi } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { MetricCard } from './components/MetricCard'; import { LiveChart } from './components/LineChart'; import { AIInsight } from './components/AIInsight';
import { useWearableSocket } from './hooks/useWearableSocket'; import type { Anomaly, Reading, SocketEvent } from './types/websocket'; import './styles.css';
const API=import.meta.env.VITE_API_BASE_URL;
export default function App(){ const [reading,setReading]=useState<Reading>(); const [history,setHistory]=useState<Record<string,unknown>[]>([]); const [alerts,setAlerts]=useState<Anomaly[]>([]); const [insight,setInsight]=useState(''); const [streaming,setStreaming]=useState(false);
 const onEvent=useCallback((event:SocketEvent)=>{ if(event.type==='sensor_update'){const r=event.data;setReading(r);setHistory(h=>[...h.slice(-59),{time:new Date(r.timestamp).toLocaleTimeString(),hr:r.heart_rate,spo2:r.spo2,movement:Math.hypot(r.accelerometer.x,r.accelerometer.y,r.accelerometer.z)}])} if(event.type==='anomaly_detected')setAlerts(a=>[event.data,...a].slice(0,8)); if(event.type==='llm_stream_start'){setInsight('');setStreaming(true)} if(event.type==='llm_stream_chunk')setInsight(t=>t+event.data.chunk); if(event.type==='llm_stream_end'||event.type==='llm_stream_error')setStreaming(false)},[]);
 const connection=useWearableSocket(onEvent); useEffect(()=>{fetch(`${API}/api/events`).then(r=>r.json()).then(setAlerts).catch(()=>{})},[]); const movement=reading?Math.hypot(reading.accelerometer.x,reading.accelerometer.y,reading.accelerometer.z):0;
 return <main><header><div><p className="eyebrow">PULSEGUARD AI</p><h1>Real-Time Wearable Intelligence Dashboard</h1></div><div className={`connection ${connection}`}><Wifi size={16}/>{connection}</div></header><section className="metrics"><MetricCard label="Heart Rate" value={reading?.heart_rate??'--'} unit="BPM"/><MetricCard label="SpO₂" value={reading?.spo2??'--'} unit="% saturation"/><MetricCard label="Movement" value={reading?movement.toFixed(2):'--'} unit="magnitude"/></section><section className="charts"><LiveChart title="Heart Rate" data={history} dataKey="hr" color="#ff5b6e"/><LiveChart title="Oxygen Saturation" data={history} dataKey="spo2" color="#4fd1ff"/><LiveChart title="Movement" data={history} dataKey="movement" color="#a78bfa"/></section><section className="lower"><AIInsight text={insight} streaming={streaming}/><article className="card alerts"><h2><ShieldAlert size={19}/> Alert Feed</h2>{alerts.length?alerts.map(a=><div className="alert" key={a.event_id}><b>{a.severity} · {(a.confidence*100).toFixed(0)}%</b><span>{new Date(a.timestamp).toLocaleString()}</span><small>{a.heart_rate} BPM · {a.spo2}% SpO₂</small></div>):<p>No anomaly events yet.</p>}</article></section><footer><Activity size={15}/> PulseGuard AI is a demonstration project and does not provide medical diagnosis or medical advice.</footer></main> }
